// source: RpcRequestOut.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var HeaderKVPair_pb = require('./HeaderKVPair_pb.js');
goog.object.extend(proto, HeaderKVPair_pb);
goog.exportSymbol('proto.Acorle.Models.RpcRequestOut', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Acorle.Models.RpcRequestOut = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Acorle.Models.RpcRequestOut.repeatedFields_, null);
};
goog.inherits(proto.Acorle.Models.RpcRequestOut, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Acorle.Models.RpcRequestOut.displayName = 'proto.Acorle.Models.RpcRequestOut';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Acorle.Models.RpcRequestOut.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Acorle.Models.RpcRequestOut.prototype.toObject = function(opt_includeInstance) {
  return proto.Acorle.Models.RpcRequestOut.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Acorle.Models.RpcRequestOut} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Acorle.Models.RpcRequestOut.toObject = function(includeInstance, msg) {
  var f, obj = {
    magic: msg.getMagic_asB64(),
    signature: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 3, 0),
    zone: jspb.Message.getFieldWithDefault(msg, 4, ""),
    key: jspb.Message.getFieldWithDefault(msg, 5, ""),
    ip: jspb.Message.getFieldWithDefault(msg, 6, ""),
    port: jspb.Message.getFieldWithDefault(msg, 7, 0),
    headersList: jspb.Message.toObjectList(msg.getHeadersList(),
    HeaderKVPair_pb.HeaderKVPair.toObject, includeInstance),
    data: msg.getData_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Acorle.Models.RpcRequestOut}
 */
proto.Acorle.Models.RpcRequestOut.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Acorle.Models.RpcRequestOut;
  return proto.Acorle.Models.RpcRequestOut.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Acorle.Models.RpcRequestOut} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Acorle.Models.RpcRequestOut}
 */
proto.Acorle.Models.RpcRequestOut.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMagic(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignature(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setZone(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setIp(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPort(value);
      break;
    case 8:
      var value = new HeaderKVPair_pb.HeaderKVPair;
      reader.readMessage(value,HeaderKVPair_pb.HeaderKVPair.deserializeBinaryFromReader);
      msg.addHeaders(value);
      break;
    case 9:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Acorle.Models.RpcRequestOut.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Acorle.Models.RpcRequestOut.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Acorle.Models.RpcRequestOut} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Acorle.Models.RpcRequestOut.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMagic_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getSignature();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getZone();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getIp();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPort();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getHeadersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      HeaderKVPair_pb.HeaderKVPair.serializeBinaryToWriter
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      9,
      f
    );
  }
};


/**
 * optional bytes magic = 1;
 * @return {!(string|Uint8Array)}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getMagic = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes magic = 1;
 * This is a type-conversion wrapper around `getMagic()`
 * @return {string}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getMagic_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMagic()));
};


/**
 * optional bytes magic = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMagic()`
 * @return {!Uint8Array}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getMagic_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMagic()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.Acorle.Models.RpcRequestOut} returns this
 */
proto.Acorle.Models.RpcRequestOut.prototype.setMagic = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional string signature = 2;
 * @return {string}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Acorle.Models.RpcRequestOut} returns this
 */
proto.Acorle.Models.RpcRequestOut.prototype.setSignature = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 timestamp = 3;
 * @return {number}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Acorle.Models.RpcRequestOut} returns this
 */
proto.Acorle.Models.RpcRequestOut.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string zone = 4;
 * @return {string}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getZone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Acorle.Models.RpcRequestOut} returns this
 */
proto.Acorle.Models.RpcRequestOut.prototype.setZone = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string key = 5;
 * @return {string}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Acorle.Models.RpcRequestOut} returns this
 */
proto.Acorle.Models.RpcRequestOut.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string ip = 6;
 * @return {string}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Acorle.Models.RpcRequestOut} returns this
 */
proto.Acorle.Models.RpcRequestOut.prototype.setIp = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 port = 7;
 * @return {number}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.Acorle.Models.RpcRequestOut} returns this
 */
proto.Acorle.Models.RpcRequestOut.prototype.setPort = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * repeated HeaderKVPair headers = 8;
 * @return {!Array<!proto.Acorle.Models.HeaderKVPair>}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getHeadersList = function() {
  return /** @type{!Array<!proto.Acorle.Models.HeaderKVPair>} */ (
    jspb.Message.getRepeatedWrapperField(this, HeaderKVPair_pb.HeaderKVPair, 8));
};


/**
 * @param {!Array<!proto.Acorle.Models.HeaderKVPair>} value
 * @return {!proto.Acorle.Models.RpcRequestOut} returns this
*/
proto.Acorle.Models.RpcRequestOut.prototype.setHeadersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.Acorle.Models.HeaderKVPair=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Acorle.Models.HeaderKVPair}
 */
proto.Acorle.Models.RpcRequestOut.prototype.addHeaders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.Acorle.Models.HeaderKVPair, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Acorle.Models.RpcRequestOut} returns this
 */
proto.Acorle.Models.RpcRequestOut.prototype.clearHeadersList = function() {
  return this.setHeadersList([]);
};


/**
 * optional bytes data = 9;
 * @return {!(string|Uint8Array)}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * optional bytes data = 9;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 9;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.Acorle.Models.RpcRequestOut.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.Acorle.Models.RpcRequestOut} returns this
 */
proto.Acorle.Models.RpcRequestOut.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 9, value);
};


goog.object.extend(exports, proto.Acorle.Models);
