// source: ServiceProto.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Acorle.Models.ServiceProto', null, global);
goog.exportSymbol('proto.Acorle.Models.ServiceProto.ServiceMessage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Acorle.Models.ServiceProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Acorle.Models.ServiceProto.repeatedFields_, null);
};
goog.inherits(proto.Acorle.Models.ServiceProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Acorle.Models.ServiceProto.displayName = 'proto.Acorle.Models.ServiceProto';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Acorle.Models.ServiceProto.ServiceMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Acorle.Models.ServiceProto.ServiceMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Acorle.Models.ServiceProto.ServiceMessage.displayName = 'proto.Acorle.Models.ServiceProto.ServiceMessage';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Acorle.Models.ServiceProto.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Acorle.Models.ServiceProto.prototype.toObject = function(opt_includeInstance) {
  return proto.Acorle.Models.ServiceProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Acorle.Models.ServiceProto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Acorle.Models.ServiceProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    servicesList: jspb.Message.toObjectList(msg.getServicesList(),
    proto.Acorle.Models.ServiceProto.ServiceMessage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Acorle.Models.ServiceProto}
 */
proto.Acorle.Models.ServiceProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Acorle.Models.ServiceProto;
  return proto.Acorle.Models.ServiceProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Acorle.Models.ServiceProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Acorle.Models.ServiceProto}
 */
proto.Acorle.Models.ServiceProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Acorle.Models.ServiceProto.ServiceMessage;
      reader.readMessage(value,proto.Acorle.Models.ServiceProto.ServiceMessage.deserializeBinaryFromReader);
      msg.addServices(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Acorle.Models.ServiceProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Acorle.Models.ServiceProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Acorle.Models.ServiceProto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Acorle.Models.ServiceProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServicesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.Acorle.Models.ServiceProto.ServiceMessage.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.Acorle.Models.ServiceProto.ServiceMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Acorle.Models.ServiceProto.ServiceMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    hash: jspb.Message.getFieldWithDefault(msg, 1, ""),
    key: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    url: jspb.Message.getFieldWithDefault(msg, 4, ""),
    weight: jspb.Message.getFieldWithDefault(msg, 5, 0),
    isprivate: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    addedtimestamp: jspb.Message.getFieldWithDefault(msg, 7, 0),
    expiretimestamp: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Acorle.Models.ServiceProto.ServiceMessage;
  return proto.Acorle.Models.ServiceProto.ServiceMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Acorle.Models.ServiceProto.ServiceMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWeight(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsprivate(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAddedtimestamp(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExpiretimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Acorle.Models.ServiceProto.ServiceMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Acorle.Models.ServiceProto.ServiceMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHash();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getIsprivate();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getAddedtimestamp();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getExpiretimestamp();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
};


/**
 * optional string hash = 1;
 * @return {string}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage} returns this
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.setHash = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string key = 2;
 * @return {string}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage} returns this
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage} returns this
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string url = 4;
 * @return {string}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage} returns this
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 weight = 5;
 * @return {number}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage} returns this
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.setWeight = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool isPrivate = 6;
 * @return {boolean}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.getIsprivate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage} returns this
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.setIsprivate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional int64 addedTimestamp = 7;
 * @return {number}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.getAddedtimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage} returns this
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.setAddedtimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 expireTimestamp = 8;
 * @return {number}
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.getExpiretimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage} returns this
 */
proto.Acorle.Models.ServiceProto.ServiceMessage.prototype.setExpiretimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * repeated ServiceMessage services = 1;
 * @return {!Array<!proto.Acorle.Models.ServiceProto.ServiceMessage>}
 */
proto.Acorle.Models.ServiceProto.prototype.getServicesList = function() {
  return /** @type{!Array<!proto.Acorle.Models.ServiceProto.ServiceMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Acorle.Models.ServiceProto.ServiceMessage, 1));
};


/**
 * @param {!Array<!proto.Acorle.Models.ServiceProto.ServiceMessage>} value
 * @return {!proto.Acorle.Models.ServiceProto} returns this
*/
proto.Acorle.Models.ServiceProto.prototype.setServicesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.Acorle.Models.ServiceProto.ServiceMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Acorle.Models.ServiceProto.ServiceMessage}
 */
proto.Acorle.Models.ServiceProto.prototype.addServices = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.Acorle.Models.ServiceProto.ServiceMessage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Acorle.Models.ServiceProto} returns this
 */
proto.Acorle.Models.ServiceProto.prototype.clearServicesList = function() {
  return this.setServicesList([]);
};


goog.object.extend(exports, proto.Acorle.Models);
